### ISSUE TITLE
PHP Warning when trying to call plugin configuration

### ISSUE THREAD

**Issue by maziminke** [SondagesPro/surveysModel#1]
After having activated the plugin at LS 2.50 and trying to go to the configuration at http://l.../index.php/admin/pluginmanager/sa/configure/id/2 I get the following PHP warning:
"in_array() expects parameter 2 to be array, null given
ls250/plugins/surveysModel/surveysModel.php(257)

257             elseif($getValues && !in_array($oUser->uid,$pluginSettings['managers']['current']))
258             {
259                 $pluginSettings['managers']['current'][]=$oUser->uid;
260             }
"

**Comment by Shnoulle** [comment]
Fixed
