### ISSUE TITLE
PHP Warning when trying to change survey settings

### ISSUE THREAD

**Issue by maziminke** [SondagesPro/surveysModel#2]
After having activated the plugin and trying to change the survey settings of any survey I get the following warning with debug mode enabled: "in_array() expects parameter 2 to be array, null given"
/var/www/vhosts/mysurveyhosting.com/httpdocs/ls250/plugins/surveysModel/surveysModel.php(352)

340      \* @return boolean
341      _/
342     private function haveReadRight($iUserID)
343     {
344         return in_array($iUserID,$this->get('users')) || $this->haveManageRight($iUserID);
345     }
346     /_*
347      \* Test is actual user have manage right on models
348      \* @return boolean
349      */
350     private function haveManageRight($iUserID)
351     {
352         return in_array($iUserID,$this->get('managers')) || Permission::model()->hasGlobalPermission("superadmin",'read', $iUserID);
353     }

**Comment by Shnoulle** [comment]
It must be fixed here : https://github.com/SondagesPro/surveysModel/commit/eb6c920803fb4870cf9850cd497dea585b8fc6b6 . And looking at file in http://extensions.sondages.pro/IMG/auto/surveysModel.zip : your plugin seems outdated.
